package com.example.model

object MotionTemplates {

    val TEMPLATES = listOf(
        MotionProject(
            id = "template_promo_sale",
            title = "FLASH SALE 50% OFF",
            subtitle = "Koleksi terbatas hanya untuk 24 jam pertama!",
            badgeText = "DISKON SPESIAL",
            ctaText = "BELI SEKARANG",
            category = "Promosi",
            aspectRatio = AspectRatioType.STORY_9_16,
            motionStyle = MotionStyle.KINETIC_POP,
            palette = MotionPalette.SUNSET_GLOW,
            particleType = ParticleType.CONFETTI,
            durationSeconds = 5.0f,
            bpm = 130,
            bounceIntensity = 1.25f,
            showGrid = true,
            showStarburst = true
        ),
        MotionProject(
            id = "template_daily_quote",
            title = "MIMPI BESAR DIMULAI DARI HARI INI",
            subtitle = "Jangan tunggu waktu sempurna, mulailah melangkah sekarang.",
            badgeText = "KATA BIJAK",
            ctaText = "BAGIKAN KE TEMAN",
            category = "Motivasi",
            aspectRatio = AspectRatioType.SQUARE_1_1,
            motionStyle = MotionStyle.ELEGANT_SMOOTH,
            palette = MotionPalette.GOLDEN_LUXURY,
            particleType = ParticleType.STARFIELD,
            durationSeconds = 6.0f,
            bpm = 95,
            bounceIntensity = 1.0f,
            showGrid = false,
            showStarburst = false
        ),
        MotionProject(
            id = "template_webinar_ai",
            title = "WEBINAR AI UNTUK PEMULA",
            subtitle = "Pelajari pembuatan konten cerdas tanpa coding rumit.",
            badgeText = "GRATIS SERTIFIKAT",
            ctaText = "DAFTAR SEAT TERBATAS",
            category = "Edukasi",
            aspectRatio = AspectRatioType.STORY_9_16,
            motionStyle = MotionStyle.NEON_PULSE,
            palette = MotionPalette.ELECTRIC_VIOLET,
            particleType = ParticleType.SPARKLES,
            durationSeconds = 5.5f,
            bpm = 120,
            bounceIntensity = 1.1f,
            showGrid = true,
            showStarburst = true
        ),
        MotionProject(
            id = "template_creator_subscribe",
            title = "VIDEO BARU SUDAH TAYANG!",
            subtitle = "Tonton tutorial lengkap di channel kami sekarang juga.",
            badgeText = "YOUTUBE PREMIERE",
            ctaText = "SUBSCRIBE & TONTON",
            category = "Medsos",
            aspectRatio = AspectRatioType.LANDSCAPE_16_9,
            motionStyle = MotionStyle.BOUNCE_ZOOM,
            palette = MotionPalette.CYBER_PUNK,
            particleType = ParticleType.CONFETTI,
            durationSeconds = 5.0f,
            bpm = 135,
            bounceIntensity = 1.2f,
            showGrid = true,
            showStarburst = true
        ),
        MotionProject(
            id = "template_cyber_gaming",
            title = "CYBER TOURNAMENT S1",
            subtitle = "Adu ketangkasan esport terbaik se-Indonesia.",
            badgeText = "PRIZE POOL 50JT",
            ctaText = "GABUNG TEAM SEKARANG",
            category = "Gaming",
            aspectRatio = AspectRatioType.LANDSCAPE_16_9,
            motionStyle = MotionStyle.CYBER_GLITCH,
            palette = MotionPalette.CYBER_PUNK,
            particleType = ParticleType.GEOMETRIC_FLOAT,
            durationSeconds = 5.2f,
            bpm = 140,
            bounceIntensity = 1.2f,
            showGrid = true,
            showStarburst = true
        ),
        MotionProject(
            id = "template_cafe_opening",
            title = "KOPI SENJA DISKON 30%",
            subtitle = "Cita rasa otentik untuk menemani harimu yang produktif.",
            badgeText = "MENU SIGNATURE",
            ctaText = "ORDER GOFOOD / GRABFOOD",
            category = "Kuliner",
            aspectRatio = AspectRatioType.STORY_9_16,
            motionStyle = MotionStyle.KINETIC_POP,
            palette = MotionPalette.SUNSET_GLOW,
            particleType = ParticleType.SPARKLES,
            durationSeconds = 4.8f,
            bpm = 115,
            bounceIntensity = 1.15f,
            showGrid = false,
            showStarburst = true
        )
    )
}
